apiVersion: v1
kind: Service
metadata:
  labels:
    app: techtrands
  name: techtrands
  namespace: {{.Values.namespace.name}}
spec:
  ports:
  - port: {{.Values.service.port}}
    protocol: {{.Values.service.protocol}}
    {{if .Values.service.targetPort}}
    targetPort: {{.Values.service.targetPort}}
    {{else }}
    targetPort: {{.Values.service.port}}
    {{end}}

  selector:
    app: techtrands
  type: {{.Values.service.type}}



