apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: techtrands
  name: techtrands
  namespace: sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: techtrands
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: techtrands
    spec:
      containers:
      - image: 0908887875/techtrends:latest
        imagePullPolicy: IfNotPresent
        name: techtrands
        ports:
        - containerPort: 3111
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3111
          initialDelaySeconds: 10
          periodSeconds: 5

        
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3111
          initialDelaySeconds: 3
          periodSeconds: 3
