apiVersion: v1
kind: Service
metadata:
  labels:
    app: techtrands
  name: techtrands
  namespace: sandbox
spec:
  ports:
  - port: 4111
    protocol: TCP
    targetPort: 3111
  selector:
    app: techtrands
  type: ClusterIP
