namespace:
  name: sandbox
 
service:
  protocol: TCP
  type: ClusterIP
  port: 4111
  targetPort: 3111

containerPort: 3111

image:
  repository: 0908887875/techtrends
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  requests: 
    memory: 64Mi 
    cpu: 250m
  limits: 
    memory: 128Mi 
    cpu: 500m

livenessProbe: 
  path: /healthz 
readinessProbe:
  path: /healthz
